name: attendancemanagementsystem
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Existing dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  collection: ^1.18.0

  # UI Enhancement
  flutter_neumorphic: ^3.2.0 # For beautiful neumorphic design
  google_fonts: ^6.1.0 # For enhanced typography
  flutter_svg: ^2.0.9 # For SVG icons
  cached_network_image: ^3.3.1 # For image caching

  # Animations
  lottie: ^2.7.0 # For Lottie animations
  animations: ^2.0.8 # For pre-built animations
  flutter_spinkit: ^5.2.0 # For loading indicators
  shimmer: ^3.0.0 # For shimmer loading effects
  flutter_staggered_animations: ^1.1.1 # For list animations

  # UI Components
  flutter_slidable: ^3.0.1 # For swipeable list items
  awesome_snackbar_content: ^0.1.3 # For enhanced snackbars
  flutter_animate: ^4.5.0 # For quick animations
  flex_color_scheme: ^7.3.1 # For beautiful color schemes

  # Dashboard Components
  fl_chart: ^0.66.0 # For charts and graphs
  table_calendar: ^3.0.9 # For calendar views
  percent_indicator: ^4.2.3 # For circular and linear indicators

  # Utility packages for UI
  timeago: ^3.6.0 # For relative time formatting
  day_night_switcher: ^0.2.0+1 # For theme switching
  bottom_navy_bar: ^6.0.0 # For beautiful bottom navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your asset paths
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
